// Generated by gencpp from file cust_msg_pub/my_first_cust_msg.msg
// DO NOT EDIT!


#ifndef CUST_MSG_PUB_MESSAGE_MY_FIRST_CUST_MSG_H
#define CUST_MSG_PUB_MESSAGE_MY_FIRST_CUST_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cust_msg_pub
{
template <class ContainerAllocator>
struct my_first_cust_msg_
{
  typedef my_first_cust_msg_<ContainerAllocator> Type;

  my_first_cust_msg_()
    : A(0)
    , B(0)
    , C(0)  {
    }
  my_first_cust_msg_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)
    , C(0)  {
  (void)_alloc;
    }



   typedef int32_t _A_type;
  _A_type A;

   typedef int32_t _B_type;
  _B_type B;

   typedef int32_t _C_type;
  _C_type C;





  typedef boost::shared_ptr< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> const> ConstPtr;

}; // struct my_first_cust_msg_

typedef ::cust_msg_pub::my_first_cust_msg_<std::allocator<void> > my_first_cust_msg;

typedef boost::shared_ptr< ::cust_msg_pub::my_first_cust_msg > my_first_cust_msgPtr;
typedef boost::shared_ptr< ::cust_msg_pub::my_first_cust_msg const> my_first_cust_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator1> & lhs, const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.C == rhs.C;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator1> & lhs, const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cust_msg_pub

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7a68ce4e0b75a9719b4950a7069c9d4";
  }

  static const char* value(const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7a68ce4e0b75a97ULL;
  static const uint64_t static_value2 = 0x19b4950a7069c9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cust_msg_pub/my_first_cust_msg";
  }

  static const char* value(const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 A\n"
"int32 B\n"
"int32 C\n"
;
  }

  static const char* value(const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_first_cust_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cust_msg_pub::my_first_cust_msg_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int32_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int32_t>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<int32_t>::stream(s, indent + "  ", v.C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUST_MSG_PUB_MESSAGE_MY_FIRST_CUST_MSG_H
