// Generated by gencpp from file srv_vect/add_num_vectorResponse.msg
// DO NOT EDIT!


#ifndef SRV_VECT_MESSAGE_ADD_NUM_VECTORRESPONSE_H
#define SRV_VECT_MESSAGE_ADD_NUM_VECTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srv_vect
{
template <class ContainerAllocator>
struct add_num_vectorResponse_
{
  typedef add_num_vectorResponse_<ContainerAllocator> Type;

  add_num_vectorResponse_()
    : sum_vect()  {
    }
  add_num_vectorResponse_(const ContainerAllocator& _alloc)
    : sum_vect(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _sum_vect_type;
  _sum_vect_type sum_vect;





  typedef boost::shared_ptr< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct add_num_vectorResponse_

typedef ::srv_vect::add_num_vectorResponse_<std::allocator<void> > add_num_vectorResponse;

typedef boost::shared_ptr< ::srv_vect::add_num_vectorResponse > add_num_vectorResponsePtr;
typedef boost::shared_ptr< ::srv_vect::add_num_vectorResponse const> add_num_vectorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srv_vect::add_num_vectorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::srv_vect::add_num_vectorResponse_<ContainerAllocator1> & lhs, const ::srv_vect::add_num_vectorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum_vect == rhs.sum_vect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::srv_vect::add_num_vectorResponse_<ContainerAllocator1> & lhs, const ::srv_vect::add_num_vectorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace srv_vect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7527e97d7b23d7f36d1b3439f809ab8";
  }

  static const char* value(const ::srv_vect::add_num_vectorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7527e97d7b23d7fULL;
  static const uint64_t static_value2 = 0x36d1b3439f809ab8ULL;
};

template<class ContainerAllocator>
struct DataType< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srv_vect/add_num_vectorResponse";
  }

  static const char* value(const ::srv_vect::add_num_vectorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] sum_vect\n"
"\n"
;
  }

  static const char* value(const ::srv_vect::add_num_vectorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum_vect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct add_num_vectorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srv_vect::add_num_vectorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srv_vect::add_num_vectorResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum_vect[]" << std::endl;
    for (size_t i = 0; i < v.sum_vect.size(); ++i)
    {
      s << indent << "  sum_vect[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.sum_vect[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRV_VECT_MESSAGE_ADD_NUM_VECTORRESPONSE_H
