// Generated by gencpp from file custom_msg_vect/num_to_add_vector.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_VECT_MESSAGE_NUM_TO_ADD_VECTOR_H
#define CUSTOM_MSG_VECT_MESSAGE_NUM_TO_ADD_VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <custom_msg_vect/num_to_add.h>

namespace custom_msg_vect
{
template <class ContainerAllocator>
struct num_to_add_vector_
{
  typedef num_to_add_vector_<ContainerAllocator> Type;

  num_to_add_vector_()
    : triple_vect()  {
    }
  num_to_add_vector_(const ContainerAllocator& _alloc)
    : triple_vect(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::custom_msg_vect::num_to_add_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::custom_msg_vect::num_to_add_<ContainerAllocator> >::other >  _triple_vect_type;
  _triple_vect_type triple_vect;





  typedef boost::shared_ptr< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> const> ConstPtr;

}; // struct num_to_add_vector_

typedef ::custom_msg_vect::num_to_add_vector_<std::allocator<void> > num_to_add_vector;

typedef boost::shared_ptr< ::custom_msg_vect::num_to_add_vector > num_to_add_vectorPtr;
typedef boost::shared_ptr< ::custom_msg_vect::num_to_add_vector const> num_to_add_vectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator1> & lhs, const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator2> & rhs)
{
  return lhs.triple_vect == rhs.triple_vect;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator1> & lhs, const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg_vect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26ee6ff0fea7723aa88681e691bd7db4";
  }

  static const char* value(const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26ee6ff0fea7723aULL;
  static const uint64_t static_value2 = 0xa88681e691bd7db4ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_vect/num_to_add_vector";
  }

  static const char* value(const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "num_to_add[] triple_vect\n"
"\n"
"================================================================================\n"
"MSG: custom_msg_vect/num_to_add\n"
"int32 A\n"
"int32 B\n"
"int32 C\n"
;
  }

  static const char* value(const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.triple_vect);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_to_add_vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_vect::num_to_add_vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_vect::num_to_add_vector_<ContainerAllocator>& v)
  {
    s << indent << "triple_vect[]" << std::endl;
    for (size_t i = 0; i < v.triple_vect.size(); ++i)
    {
      s << indent << "  triple_vect[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::custom_msg_vect::num_to_add_<ContainerAllocator> >::stream(s, indent + "    ", v.triple_vect[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_VECT_MESSAGE_NUM_TO_ADD_VECTOR_H
