// Generated by gencpp from file custom_msg_vect/num_to_add.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_VECT_MESSAGE_NUM_TO_ADD_H
#define CUSTOM_MSG_VECT_MESSAGE_NUM_TO_ADD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg_vect
{
template <class ContainerAllocator>
struct num_to_add_
{
  typedef num_to_add_<ContainerAllocator> Type;

  num_to_add_()
    : A(0)
    , B(0)
    , C(0)  {
    }
  num_to_add_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)
    , C(0)  {
  (void)_alloc;
    }



   typedef int32_t _A_type;
  _A_type A;

   typedef int32_t _B_type;
  _B_type B;

   typedef int32_t _C_type;
  _C_type C;





  typedef boost::shared_ptr< ::custom_msg_vect::num_to_add_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_vect::num_to_add_<ContainerAllocator> const> ConstPtr;

}; // struct num_to_add_

typedef ::custom_msg_vect::num_to_add_<std::allocator<void> > num_to_add;

typedef boost::shared_ptr< ::custom_msg_vect::num_to_add > num_to_addPtr;
typedef boost::shared_ptr< ::custom_msg_vect::num_to_add const> num_to_addConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_vect::num_to_add_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_vect::num_to_add_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg_vect::num_to_add_<ContainerAllocator1> & lhs, const ::custom_msg_vect::num_to_add_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.C == rhs.C;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg_vect::num_to_add_<ContainerAllocator1> & lhs, const ::custom_msg_vect::num_to_add_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg_vect

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_vect::num_to_add_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_vect::num_to_add_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_vect::num_to_add_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7a68ce4e0b75a9719b4950a7069c9d4";
  }

  static const char* value(const ::custom_msg_vect::num_to_add_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7a68ce4e0b75a97ULL;
  static const uint64_t static_value2 = 0x19b4950a7069c9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_vect/num_to_add";
  }

  static const char* value(const ::custom_msg_vect::num_to_add_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 A\n"
"int32 B\n"
"int32 C\n"
;
  }

  static const char* value(const ::custom_msg_vect::num_to_add_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.C);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct num_to_add_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_vect::num_to_add_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_vect::num_to_add_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int32_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int32_t>::stream(s, indent + "  ", v.B);
    s << indent << "C: ";
    Printer<int32_t>::stream(s, indent + "  ", v.C);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_VECT_MESSAGE_NUM_TO_ADD_H
